.github/workflows/pages.yml
name: Pages

# 自动部署触发条件：main分支更新
on:
  push:
    branches:
      - main

jobs:
  pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout codes 
        uses: actions/checkout@v2
        
      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: "18"
          
      # 设置包缓存目录，避免每次下载
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
            
      - name: Install Dependencies
        run: |
          npm install -g hexo-cli
          npm install
        
      - name: Generate files
        run: |
          hexo clean
          hexo generate
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.HEXO_DEPLOY_KEY }}
          publish_dir: ./public